# Kubernetes Secrets Manifest v1.28+
# Security Controls:
# - AES-256-GCM encryption
# - 90-day key rotation
# - RBAC with namespace isolation
# - Encrypted etcd backups
# - Audit logging enabled
# Compliance: SOC 2 Type II, GDPR, PCI DSS

---
# Database Credentials Secret
apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: ${ENVIRONMENT}
  labels:
    app.kubernetes.io/name: database-credentials
    app.kubernetes.io/part-of: ai-detection-platform
    rotation.kubernetes.io/schedule: "90d"
  annotations:
    encryption.kubernetes.io/algorithm: AES-256-GCM
    rotation.kubernetes.io/last-rotated: timestamp
type: Opaque
data:
  POSTGRES_USER: base64_encoded_value
  POSTGRES_PASSWORD: base64_encoded_value
  MONGODB_URI: base64_encoded_value
  REDIS_PASSWORD: base64_encoded_value

---
# Elasticsearch Credentials Secret
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-credentials
  namespace: ${ENVIRONMENT}
  labels:
    app.kubernetes.io/name: elasticsearch-credentials
    app.kubernetes.io/part-of: ai-detection-platform
    rotation.kubernetes.io/schedule: "90d"
type: Opaque
data:
  ELASTICSEARCH_USERNAME: base64_encoded_value
  ELASTICSEARCH_PASSWORD: base64_encoded_value
  ELASTICSEARCH_CA_CERT: base64_encoded_value

---
# JWT Secrets
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secrets
  namespace: ${ENVIRONMENT}
  labels:
    app.kubernetes.io/name: jwt-secrets
    app.kubernetes.io/part-of: ai-detection-platform
    rotation.kubernetes.io/schedule: "90d"
type: Opaque
data:
  JWT_SECRET: base64_encoded_value
  JWT_PRIVATE_KEY: base64_encoded_value
  JWT_PUBLIC_KEY: base64_encoded_value
  JWT_REFRESH_SECRET: base64_encoded_value

---
# OAuth Credentials
apiVersion: v1
kind: Secret
metadata:
  name: oauth-credentials
  namespace: ${ENVIRONMENT}
  labels:
    app.kubernetes.io/name: oauth-credentials
    app.kubernetes.io/part-of: ai-detection-platform
type: Opaque
data:
  AUTH0_CLIENT_ID: base64_encoded_value
  AUTH0_CLIENT_SECRET: base64_encoded_value
  AUTH0_DOMAIN: base64_encoded_value
  AUTH0_CALLBACK_URL: base64_encoded_value

---
# AI Service Secrets
apiVersion: v1
kind: Secret
metadata:
  name: ai-service-secrets
  namespace: ${ENVIRONMENT}
  labels:
    app.kubernetes.io/name: ai-service-secrets
    app.kubernetes.io/part-of: ai-detection-platform
    rotation.kubernetes.io/schedule: "90d"
type: Opaque
data:
  OPENAI_API_KEY: base64_encoded_value
  MODEL_ENCRYPTION_KEY: base64_encoded_value
  MODEL_SIGNING_KEY: base64_encoded_value
  AI_SERVICE_API_KEY: base64_encoded_value

---
# TLS Certificates
apiVersion: v1
kind: Secret
metadata:
  name: tls-certificates
  namespace: ${ENVIRONMENT}
  labels:
    app.kubernetes.io/name: tls-certificates
    app.kubernetes.io/part-of: ai-detection-platform
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
    cert-manager.io/renewal-window: "720h"
type: kubernetes.io/tls
data:
  tls.crt: base64_encoded_certificate
  tls.key: base64_encoded_private_key
  ca.crt: base64_encoded_ca_certificate