# Istio Service Mesh Configuration for AI-Powered Detection Platform
# Version: 1.20.0

# Global settings applied across all Istio components
global:
  # Namespace where Istio components will be installed
  istioNamespace: istio-system
  
  # Container registry and version settings
  hub: docker.io/istio
  tag: 1.20.0
  
  # Proxy configuration applied to all sidecars
  proxy:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 2000m
        memory: 1Gi
    # Tracing configuration
    tracer: jaeger
    # Access logging settings
    accessLogFile: /dev/stdout
    accessLogFormat: json
    logLevel: info

  # Mutual TLS settings
  mtls:
    enabled: true
    auto: true

  # Multi-cluster support (disabled for single cluster deployment)
  multiCluster:
    enabled: false

  # Mesh-wide configuration
  meshConfig:
    enableTracing: true
    defaultConfig:
      tracing:
        sampling: 100
        zipkin:
          address: jaeger-collector.monitoring:9411
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: "true"
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"

# Istiod (Control Plane) configuration
pilot:
  enabled: true
  autoscaleEnabled: true
  autoscaleMin: 2
  autoscaleMax: 5
  replicaCount: 2
  resources:
    requests:
      cpu: 500m
      memory: 2048Mi
    limits:
      cpu: 1000m
      memory: 4096Mi
  env:
    PILOT_TRACE_SAMPLING: "100"
  traceSampling: 100

# Gateway configurations
gateways:
  istio-ingressgateway:
    enabled: true
    labels:
      app: istio-ingressgateway
      istio: ingressgateway
    replicaCount: 2
    autoscaleEnabled: true
    autoscaleMin: 2
    autoscaleMax: 5
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 2000m
        memory: 1Gi
    type: LoadBalancer
    ports:
      - name: http2
        port: 80
        targetPort: 80
      - name: https
        port: 443
        targetPort: 443

  istio-egressgateway:
    enabled: true
    labels:
      app: istio-egressgateway
      istio: egressgateway
    replicaCount: 2
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 2000m
        memory: 1Gi

# Sidecar injector configuration
sidecarInjectorWebhook:
  enabled: true
  rewriteAppHTTPProbe: true

# Prometheus integration for metrics collection
prometheus:
  enabled: true
  scrapeInterval: "15s"

# Distributed tracing configuration
tracing:
  enabled: true
  provider: jaeger

# Kiali dashboard configuration
kiali:
  enabled: true
  dashboard:
    auth:
      strategy: token
    viewOnlyMode: false